import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Searchbar from "../components/searchBar/Searchbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Fusion",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="relative bg-black">
					<div className="absolute top-0 left-0 w-full h-full">
						<img
							src="/background.png"
							alt="background"
							className="h-screen w-full object-cover"
						/>
					</div>

					<div className="absolute top-0 left-0 w-full h-screen bg-gradient-to-b from-black/10 to-black" />
					<div className="relative">
						<Searchbar />
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
